# Generated by Django 2.0.4 on 2018-05-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='dayq_rent',
            new_name='day_rent',
        ),
    ]
