# Generated by Django 2.0.4 on 2018-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testin', '0002_auto_20180502_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent_buy',
            field=models.BooleanField(),
        ),
    ]
